name: action workflow

on: [push]

jobs:
  runs-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: simple js action
        id: great
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: rushi
      - name: Log Greeting Time
        run: echo "${{steps.great.outputs.time}}"
    