name: container
on: push

jobs: 
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: docker:20.10.21-git
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release  